language: cpp
matrix:
    include:
        - os: osx
          osx_image: xcode10.2
          compiler: clang
          install:
              - pip install conan
              - conan user
          script:
              - conan remote add public-conan https://api.bintray.com/conan/bincrafters/public-conan True
              - conan install .
              - cmake .
              - cmake --build .
              - ctest
          addons:
              homebrew:
                  packages:
                      - mongodb
          before_install:
              - brew services start mongodb
        - os: linux
          dist: xenial
          compiler: gcc
          services: mongodb
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-8
          env:
              - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
          install:
              - pip install --user conan
              - conan user
          script:
              - conan remote add public-conan https://api.bintray.com/conan/bincrafters/public-conan True
              - conan install . -s compiler.libcxx=libstdc++11 --build missing
              - cmake .
              - cmake --build .
              - ctest
          before_install:
              - eval "${MATRIX_EVAL}"
