matrix:
    include:
        os: osx
        osx_image: xcode10.2
        language: cpp
        compiler:
            - clang
        install:
            - pip install conan
            - conan user
        script:
            - conan remote add public-conan https://api.bintray.com/conan/bincrafters/public-conan True
            - conan install .
            - cmake .
            - cmake --build .
            - ctest
    include:
        os: linux
        dist: xenial
        language: cpp
        compiler: gcc
        addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - g++-8
        env:
            - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
        install:
            - pip install --user conan
            - conan user
        script:
            - conan remote add public-conan https://api.bintray.com/conan/bincrafters/public-conan True
            - conan install . -s compiler.libcxx=libstdc++11 --build missing
            - cmake .
            - cmake --build .
            - ctest
        before_install:
            - eval "${MATRIX_EVAL}"
