@startuml
namespace controller {
    interface Controller {
        + execute()
    }
    class Amount
    class Transfer
    class TransferSend

    Controller <|.. Amount
    Controller <|.. Transfer
    Controller <|.. TransferSend
}
@enduml