@startuml
hide empty members
namespace db {
    interface Query {
        + where(condition)
        + execute()
        + get(name : string, value [out])
    }
    interface Command {
        + set(name : string, value)
        + execute()
    }
    interface Factory {
        + query() : Query
        + command() : Command
    }
    class MongoCommand
    class MongoQuery
    class MongoFactory


    Query <|.. MongoQuery
    Command <|.. MongoCommand
    Factory <|.. MongoFactory
    MongoCommand <.. MongoFactory : create
    MongoQuery <.. MongoFactory : create
}
@enduml
