@startuml
hide empty members
namespace model {
    class Variant {
        int
        string
        long long
    }
    abstract class Table {
        - fields : BaseFieldList
        + save()
        + fetch(field: BaseField)
        + {static} load() : TableList
    }
    abstract class BaseField {
        - name : string
        - value : Variant
        - table : Table
        + set(value : Variant)
        + get() : Variant
        + load()
    }
    class Field << template >> {
    }
    class User {
        + id : Int
        + name : Text
        + amount : LongLong
    }
    class Transfer {
        + id : Int
        + sender : Int
        + recipient : Int
        + amount : LongLong
        + description : Text
    }

    BaseField .> Variant
    BaseField <|-- Field
    Field <|-- Int
    Field <|-- Text
    Field <|-- LongLong
    Table "1" .o BaseField
    Table o. "*" BaseField
    Table <|-- User
    Table <|-- Transfer
    Transfer o. "2" User
}
@enduml
